services:
  a2c:
    image: rlcj
    environment:
      - RLCJ_ALGORITHM=A2C
    volumes:
      - ./output/a2c:/tmp/rl_out
  ppo:
    image: rlcj
    environment:
      - RLCJ_ALGORITHM=PPO
    volumes:
      - ./output/ppo:/tmp/rl_out
  td3:
    image: rlcj
    environment:
      - RLCJ_ALGORITHM=TD3
    volumes:
      - ./output/td3:/tmp/rl_out
  
